INSERT INTO `bezantrakta_location_city` (`id`, `title`, `slug`, `timezone`, `state`) VALUES
(383, 'Новосибирск', 'nsk', 'Asia/Novosibirsk', 0),
(391, 'Красноярск', 'krsk', 'Asia/Krasnoyarsk', 0),
(423, 'Владивосток', 'vl', 'Asia/Vladivostok', 0),
(473, 'Воронеж', 'vrn', 'Europe/Moscow', 1),
(484, 'Обнинск', 'obn', 'Europe/Moscow', 0),
(831, 'Нижний Новгород', 'nnov', 'Europe/Moscow', NULL),
(846, 'Самара', 'sam', 'Europe/Samara', 0),
(861, 'Краснодар', 'krd', 'Europe/Moscow', 1),
(863, 'Ростов-на-Дону', 'rnd', 'Europe/Moscow', NULL),
(3022, 'Чита', 'chita', 'Asia/Yakutsk', 0),
(3452, 'Тюмень', 'tyu', 'Asia/Yekaterinburg', 0),
(3462, 'Сургут', 'sur', 'Asia/Yekaterinburg', NULL),
(3466, 'Нижневартовск', 'nvar', 'Asia/Yekaterinburg', 0),
(3532, 'Оренбург', 'oren', 'Asia/Yekaterinburg', 0),
(3812, 'Омск', 'omsk', 'Asia/Omsk', 0),
(3952, 'Иркутск', 'irk', 'Asia/Irkutsk', 0),
(4012, 'Калининград', 'kgd', 'Europe/Kaliningrad', 0),
(4162, 'Благовещенск', 'blag', 'Asia/Yakutsk', 0),
(4212, 'Хабаровск', 'hab', 'Asia/Vladivostok', 0),
(4234, 'Уссурийск', 'ussur', 'Asia/Vladivostok', 0),
(4242, 'Южно-Сахалинск', 'ysah', 'Asia/Sakhalin', 0),
(4712, 'Курск', 'kur', 'Europe/Moscow', 1),
(4722, 'Белгород', 'bel', 'Europe/Moscow', 1),
(4725, 'Старый Оскол', 'osk', 'Europe/Moscow', 0),
(4742, 'Липецк', 'lip', 'Europe/Moscow', 1),
(4752, 'Тамбов', 'tam', 'Europe/Moscow', NULL),
(4812, 'Смоленск', 'smol', 'Europe/Moscow', 0),
(4822, 'Тверь', 'tver', 'Europe/Moscow', 0),
(4832, 'Брянск', 'bry', 'Europe/Moscow', 0),
(4842, 'Калуга', 'kal', 'Europe/Moscow', 0),
(4852, 'Ярославль', 'yar', 'Europe/Moscow', 0),
(4862, 'Орел', 'orel', 'Europe/Moscow', 1),
(4872, 'Тула', 'tula', 'Europe/Moscow', 0),
(4912, 'Рязань', 'rzn', 'Europe/Moscow', 0),
(4922, 'Владимир', 'vlad', 'Europe/Moscow', 0),
(4932, 'Иваново', 'ivan', 'Europe/Moscow', 0),
(4942, 'Кострома', 'kos', 'Europe/Moscow', 0),
(8112, 'Псков', 'psk', 'Europe/Moscow', 0),
(8162, 'Великий Новгород', 'vnov', 'Europe/Moscow', 0),
(8172, 'Вологда', 'vo', 'Europe/Moscow', 0),
(8182, 'Архангельск', 'arh', 'Europe/Moscow', NULL),
(8412, 'Пенза', 'pnz', 'Europe/Moscow', 0),
(8422, 'Ульяновск', 'uly', 'Europe/Moscow', 0),
(8442, 'Волгоград', 'vol', 'Europe/Volgograd', 0),
(8452, 'Саратов', 'sar', 'Europe/Volgograd', 1),
(8482, 'Тольятти', 'tlt', 'Europe/Samara', 0),
(81153, 'Великие Луки', 'vluki', 'Europe/Moscow', NULL),
(81842, 'Северодвинск', 'sdvin', 'Europe/Moscow', 0);
