# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.IntegerField(help_text='Идентификатор города - его телефонный код.', primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('slug', models.SlugField(max_length=8, verbose_name='Псевдоним')),
                ('timezone', timezone_field.fields.TimeZoneField(default='Europe/Moscow', verbose_name='Часовой пояс')),
                ('state', models.NullBooleanField(choices=[(False, 'отключен'), (None, 'подготовка'), (True, 'включен')], default=False, help_text='<ul><li>отключен - НЕ виден в списке городов и НЕ работает;</li><li>подготовка - виден в списке городов, но НЕ доступен для выбора (скоро открытие);</li><li>включен - виден в списке городов и работает.</li></ul>', verbose_name='Состояние')),
            ],
            options={
                'verbose_name_plural': 'города',
                'verbose_name': 'город',
                'db_table': 'bezantrakta_location_city',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.IntegerField(help_text='Идентификатор сайта - число из 3-х цифр.<br>Первые 2 цифры - автомобильный код региона, в котором находится город сайта.<br>Третья цифра - порядковый номер от 0 до 9.', primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('slug', models.CharField(max_length=32, unique=True, verbose_name='Псевдоним')),
                ('is_published', models.BooleanField(default=False, help_text='<ul><li>опубликован - включен и работает;</li><li>НЕ опубликован - отключен (сайт недоступен, проводятся технические работы).</li></ul>', verbose_name='Публикация')),
                ('city', models.ForeignKey(db_column='city_id', on_delete=django.db.models.deletion.CASCADE, to='location.City', verbose_name='Город')),
            ],
            options={
                'verbose_name_plural': 'сайты',
                'verbose_name': 'сайт',
                'db_table': 'bezantrakta_location_domain',
                'ordering': ('city', 'title'),
            },
        ),
    ]
