# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 14:38
from __future__ import unicode_literals

import bezantrakta.location.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='settings',
            field=models.TextField(default=bezantrakta.location.models.get_default_domain_settings, verbose_name='Настройки в JSON'),
        ),
    ]
