# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 08:34
from __future__ import unicode_literals

import bezantrakta.banner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannergroupitem',
            name='img',
            field=models.ImageField(upload_to=bezantrakta.banner.models.img_path, verbose_name='Изображение'),
        ),
    ]
