# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 08:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0005_auto_20170529_0851'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bannergroup',
            table='bezantrakta_banner_group',
        ),
    ]
