# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0009_auto_20170529_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannergroupitem',
            name='domain',
            field=models.ForeignKey(db_column='domain_id', on_delete=django.db.models.deletion.CASCADE, to='domain.Domain', verbose_name='Домен'),
        ),
    ]
