# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 07:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domain', '0006_auto_20170524_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32, verbose_name='Название группы баннеров')),
                ('slug', models.SlugField(max_length=32, verbose_name='Псевдоним группы баннеров')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Группа баннеров',
                'verbose_name_plural': 'Группы баннеров',
                'ordering': ('title', 'order'),
                'db_table': 'bezantrakta_banner',
            },
        ),
        migrations.CreateModel(
            name='BannerGroupItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32, verbose_name='Название баннера')),
                ('slug', models.SlugField(max_length=32, verbose_name='Псевдоним баннера')),
                ('img', models.ImageField(upload_to='upload/banner/', verbose_name='Изображение')),
                ('href', models.URLField(verbose_name='Внешняя ссылка')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='Сохранено')),
                ('banner_group', models.ForeignKey(db_column='banner_group_id', on_delete=django.db.models.deletion.CASCADE, to='banner.BannerGroup', verbose_name='Баннер')),
                ('domain', models.ForeignKey(blank=True, db_column='domain_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='domain.Domain', verbose_name='Домен')),
            ],
            options={
                'verbose_name': 'Баннер',
                'db_table': 'bezantrakta_banner_group_item',
                'verbose_name_plural': 'Баннеры',
                'ordering': ('title', 'order'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='bannergroupitem',
            unique_together=set([('domain', 'banner_group', 'slug')]),
        ),
    ]
