# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_auto_20170529_0834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannergroupitem',
            options={'ordering': ('order', 'banner_group', 'domain', 'title'), 'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеры'},
        ),
    ]
