# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0003_auto_20170529_0842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannergroup',
            options={'ordering': ('order', 'title'), 'verbose_name': 'Группа баннеров', 'verbose_name_plural': 'Группы баннеров'},
        ),
    ]
