# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0007_auto_20170529_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannergroupitem',
            name='banner_group',
            field=models.ForeignKey(db_column='banner_group_id', on_delete=django.db.models.deletion.CASCADE, to='banner.BannerGroup', verbose_name='Группа баннеров'),
        ),
    ]
