# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0008_auto_20170529_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannergroupitem',
            name='href',
            field=models.URLField(blank=True, verbose_name='Внешняя ссылка'),
        ),
    ]
