# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('city_title', models.CharField(max_length=64, verbose_name='Название города')),
                ('city_slug', models.SlugField(max_length=64, verbose_name='Псевдоним города')),
                ('city_status', models.BooleanField(default=False, help_text='True - готов к работе, False - скоро открытие', verbose_name='Готов ли город к работе')),
            ],
            options={
                'verbose_name': 'Город',
                'ordering': ('city_title',),
                'verbose_name_plural': 'Города',
                'db_table': 'bezantrakta_city',
            },
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['city_id'], name='bezantrakta_city_id_ed6615_idx'),
        ),
    ]
