# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 21:50
from __future__ import unicode_literals

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='Europe/Moscow', verbose_name='Часовой пояс'),
        ),
    ]
