# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0003_auto_20170524_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(max_length=8, verbose_name='Псевдоним города'),
        ),
    ]
