# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(help_text='Должно сдержать ключевые слова или фразы,\n        описывающие событие, но не более 3-5 раз.\n\n        Всего не более 150-200 символов', max_length=200, verbose_name='Метатег `description`'),
        ),
        migrations.AlterField(
            model_name='article',
            name='keywords',
            field=models.CharField(help_text='Несколько ключевых слов или фраз,\n        разделённых запятыми, которые описывают содержимое текста.\n\n        Всего не более 100-150 символов', max_length=150, verbose_name='Метатег `keywords`'),
        ),
    ]
