# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20170524_1325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('domain', 'title'), 'verbose_name': 'HTML-страница', 'verbose_name_plural': 'HTML-страницы'},
        ),
    ]
