# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20170529_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='update_datetime',
        ),
    ]
