# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 07:37
from __future__ import unicode_literals

import bezantrakta.event.models.container_binder
import bezantrakta.event.models.link
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    replaces = [('event', '0001_squashed_0005_auto_20170606_1400'), ('event', '0002_auto_20170607_0720'), ('event', '0003_auto_20170607_0722'), ('event', '0004_auto_20170607_0722'), ('event', '0005_auto_20170607_0729'), ('event', '0006_auto_20170607_0729'), ('event', '0007_remove_event_datetime')]

    initial = True

    dependencies = [
        ('location', '0002_city_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Всего не более 60-65 символов', max_length=64, verbose_name='Название')),
                ('slug', models.SlugField(max_length=64, verbose_name='Псевдоним')),
                ('description', models.TextField(help_text='Должно сдержать ключевые слова или фразы,\n        описывающие событие, но не более 3-5 раз.\n\n        Всего не более 150-200 символов', max_length=200, verbose_name='Метатег `description`')),
                ('keywords', models.TextField(help_text='Несколько ключевых слов или фраз,\n        разделённых запятыми, которые описывают содержимое текста.\n\n        Всего не более 100-150 символов', max_length=150, verbose_name='Метатег `keywords`')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Описание события')),
                ('is_published', models.BooleanField(default=False, verbose_name='Публикация')),
                ('is_on_index', models.BooleanField(default=False, verbose_name='На главной')),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Минимальная цена билета')),
                ('min_age', models.PositiveSmallIntegerField(choices=[(0, '0+'), (6, '6+'), (12, '12+'), (16, '16+'), (18, '18+')], default=0, verbose_name='Возрастное ограничение')),
                ('datetime', models.DateTimeField(verbose_name='Дата/время события')),
                ('domain', models.ForeignKey(db_column='domain_id', on_delete=django.db.models.deletion.CASCADE, to='location.Domain', verbose_name='Домен')),
            ],
            options={
                'verbose_name_plural': 'События',
                'ordering': ('domain', 'datetime', 'title'),
                'verbose_name': 'Событие',
                'db_table': 'bezantrakta_event',
            },
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Всего не более 60-65 символов', max_length=64, verbose_name='Название')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='Псевдоним')),
                ('description', models.CharField(help_text='Должно сдержать ключевые слова или фразы,\n        описывающие событие, но не более 3-5 раз.\n\n        Всего не более 150-200 символов', max_length=200, verbose_name='Метатег `description`')),
                ('keywords', models.CharField(help_text='Несколько ключевых слов или фраз,\n        разделённых запятыми, которые описывают содержимое текста.\n\n        Всего не более 100-150 символов', max_length=150, verbose_name='Метатег `keywords`')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
            ],
            options={
                'verbose_name_plural': 'категории событий',
                'ordering': ('title',),
                'verbose_name': 'категория событий',
                'db_table': 'bezantrakta_event_category',
            },
        ),
        migrations.CreateModel(
            name='EventContainer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32, verbose_name='Название')),
                ('slug', models.SlugField(max_length=32, verbose_name='Псевдоним')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
                ('img_width', models.PositiveSmallIntegerField(verbose_name='Ширина афиши')),
                ('img_height', models.PositiveSmallIntegerField(verbose_name='Высота афиши')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
            ],
            options={
                'verbose_name_plural': 'Контейнеры',
                'ordering': ('order', 'is_published', 'title'),
                'verbose_name': 'Контейнер',
                'db_table': 'bezantrakta_event_container',
            },
        ),
        migrations.CreateModel(
            name='EventContainerBinder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок в контейнере')),
                ('img', models.ImageField(blank=True, null=True, upload_to=bezantrakta.event.models.container_binder.img_path, verbose_name='Афиша')),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, to='event.Event', verbose_name='Событие')),
                ('event_container', models.ForeignKey(db_column='event_container_id', on_delete=django.db.models.deletion.CASCADE, to='event.EventContainer', verbose_name='Группа событий')),
            ],
            options={
                'verbose_name_plural': 'Связь событий и контейнеров событий',
                'verbose_name': 'Связь событий и контейнеров событий',
                'db_table': 'bezantrakta_event_container_binder',
            },
        ),
        migrations.CreateModel(
            name='EventGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Всего не более 60-65 символов', max_length=64, verbose_name='Название')),
                ('slug', models.SlugField(max_length=64, verbose_name='Псевдоним')),
                ('is_published', models.BooleanField(default=False, verbose_name='Публикация')),
                ('is_on_index', models.BooleanField(default=False, verbose_name='На главной')),
                ('domain', models.ForeignKey(db_column='domain_id', on_delete=django.db.models.deletion.CASCADE, to='location.Domain', verbose_name='Домен')),
            ],
            options={
                'verbose_name_plural': 'Группы событий',
                'ordering': ('id', 'title'),
                'verbose_name': 'Группа событий',
                'db_table': 'bezantrakta_event_group',
            },
        ),
        migrations.CreateModel(
            name='EventGroupBinder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, to='event.Event', verbose_name='Событие')),
                ('event_group', models.ForeignKey(db_column='event_group_id', on_delete=django.db.models.deletion.CASCADE, to='event.EventGroup', verbose_name='Группа событий')),
            ],
            options={
                'verbose_name_plural': 'связки событий и групп событий',
                'verbose_name': 'связка событий и групп событий',
                'db_table': 'bezantrakta_event_group_binder',
            },
        ),
        migrations.CreateModel(
            name='EventVenue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Всего не более 60-65 символов', max_length=64, verbose_name='Название')),
                ('slug', models.SlugField(max_length=64, verbose_name='Псевдоним')),
                ('domain', models.ForeignKey(db_column='domain_id', on_delete=django.db.models.deletion.CASCADE, to='location.Domain', verbose_name='Домен')),
            ],
            options={
                'verbose_name_plural': 'Залы',
                'ordering': ('domain', 'title'),
                'verbose_name': 'Зал',
                'db_table': 'bezantrakta_event_venue',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='event_category',
            field=models.ForeignKey(blank=True, db_column='event_category_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='event.EventCategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_container',
            field=models.ManyToManyField(blank=True, through='event.EventContainerBinder', to='event.EventContainer', verbose_name='Контейнеры, в которых отображается событие'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_group',
            field=models.ManyToManyField(blank=True, through='event.EventGroupBinder', to='event.EventGroup', verbose_name='Группа, в которую входит событие'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_venue',
            field=models.ForeignKey(db_column='event_venue_id', on_delete=django.db.models.deletion.CASCADE, to='event.EventVenue', verbose_name='Зал'),
        ),
        migrations.AlterUniqueTogether(
            name='eventvenue',
            unique_together=set([('domain', 'slug')]),
        ),
        migrations.AlterUniqueTogether(
            name='eventgroup',
            unique_together=set([('domain', 'slug')]),
        ),
        migrations.AlterUniqueTogether(
            name='eventcontainerbinder',
            unique_together=set([('event', 'event_container', 'order')]),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set([('domain', 'datetime', 'slug')]),
        ),
        migrations.CreateModel(
            name='EventLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32, verbose_name='Название')),
                ('slug', models.SlugField(max_length=32, verbose_name='Псевдоним')),
                ('img', models.ImageField(blank=True, help_text='Размер логотипа 200x32 px', null=True, upload_to=bezantrakta.event.models.link.img_path, verbose_name='Логотип')),
            ],
            options={
                'verbose_name_plural': 'ссылки',
                'ordering': ('title',),
                'verbose_name': 'ссылка',
                'db_table': 'bezantrakta_event_link',
            },
        ),
        migrations.CreateModel(
            name='EventLinkBinder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.URLField(blank=True, verbose_name='Внешняя ссылка')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
            ],
            options={
                'verbose_name_plural': 'связь событий и ссылок',
                'ordering': ('order', 'event', 'event_link'),
                'verbose_name': 'связь событий и ссылок',
                'db_table': 'bezantrakta_event_link_binder',
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('domain', 'datetime', 'title'), 'verbose_name': 'событие', 'verbose_name_plural': 'события'},
        ),
        migrations.AlterModelOptions(
            name='eventcontainer',
            options={'ordering': ('order', 'is_published', 'title'), 'verbose_name': 'контейнер', 'verbose_name_plural': 'контейнеры'},
        ),
        migrations.AlterModelOptions(
            name='eventcontainerbinder',
            options={'ordering': ('order', 'event', 'event_container'), 'verbose_name': 'связь событий и контейнеров', 'verbose_name_plural': 'связь событий и контейнеров'},
        ),
        migrations.AlterModelOptions(
            name='eventgroup',
            options={'ordering': ('id', 'title'), 'verbose_name': 'группа событий', 'verbose_name_plural': 'группы событий'},
        ),
        migrations.AlterModelOptions(
            name='eventvenue',
            options={'ordering': ('domain', 'title'), 'verbose_name': 'зал', 'verbose_name_plural': 'залы'},
        ),
        migrations.AddField(
            model_name='eventlinkbinder',
            name='event',
            field=models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, to='event.Event', verbose_name='Событие'),
        ),
        migrations.AddField(
            model_name='eventlinkbinder',
            name='event_link',
            field=models.ForeignKey(db_column='event_link_id', on_delete=django.db.models.deletion.CASCADE, to='event.EventLink', verbose_name='Ссылки'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_link',
            field=models.ManyToManyField(blank=True, through='event.EventLinkBinder', to='event.EventLink', verbose_name='Ссылки, добавленные к событию'),
        ),
        migrations.AlterUniqueTogether(
            name='eventlinkbinder',
            unique_together=set([('event', 'event_link')]),
        ),
        migrations.AlterField(
            model_name='eventcontainer',
            name='img_height',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Высота афиши'),
        ),
        migrations.AlterField(
            model_name='eventcontainer',
            name='img_width',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ширина афиши'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(max_length=64, unique_for_date='datetime', verbose_name='Псевдоним'),
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата события'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Время начала события'),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('domain', 'date', 'time', 'title'), 'verbose_name': 'событие', 'verbose_name_plural': 'события'},
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(max_length=64, unique_for_date='date', verbose_name='Псевдоним'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='datetime',
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set([('domain', 'date', 'slug')]),
        ),
    ]
