# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 07:43
from __future__ import unicode_literals

from django.utils import timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_eventcontainer_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='datetime',
            field=models.DateTimeField(default=timezone.now, verbose_name='Дата и время'),
        ),
    ]
