# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20170613_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(max_length=64, verbose_name='Псевдоним'),
        ),
    ]
