# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_domain_settings'),
        ('event', '0003_event_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('domain', 'datetime', 'title'), 'verbose_name': 'событие', 'verbose_name_plural': 'события'},
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set([('domain', 'datetime', 'slug')]),
        ),
    ]
