# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20170608_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlinkbinder',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
