# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_ticket_service_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_service_venue',
            field=models.PositiveIntegerField(blank=True, db_column='ticket_service_venue_id', null=True, verbose_name='ID зала в сервисе продажи билетов'),
        ),
    ]
