# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_ticket_service_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_venue',
            field=models.ForeignKey(blank=True, db_column='event_venue_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='event.EventVenue', verbose_name='Зал'),
        ),
    ]
