# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(help_text='Содержит ключевые слова или фразы, описывающие страницу, но не более 3-5 шт.<br>Всего не более 150-200 символов.', max_length=200, verbose_name='Метатег `description`'),
        ),
        migrations.AlterField(
            model_name='article',
            name='domain',
            field=models.ForeignKey(db_column='domain_id', on_delete=django.db.models.deletion.CASCADE, to='location.Domain', verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='article',
            name='keywords',
            field=models.TextField(help_text='Несколько ключевых слов или фраз, разделённых запятыми, которые описывают содержимое страницы.<br>Всего не более 100-150 символов.', max_length=150, verbose_name='Метатег `keywords`'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='Всего не более 60-65 символов.', max_length=64, verbose_name='title'),
        ),
    ]
