# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 08:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_city_is_published'),
        ('article', '0002_auto_20170602_0850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('domain', 'title', 'is_published'), 'verbose_name': 'HTML-страница', 'verbose_name_plural': 'HTML-страницы'},
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together=set([('domain', 'slug')]),
        ),
    ]
