# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20170524_1024'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='article',
            name='bezantrakta_id_11f1ed_idx',
        ),
    ]
