# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
        ('ticket_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_service',
            field=models.ForeignKey(blank=True, db_column='ticket_service_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket_service.TicketService', verbose_name='Сервис продажи билетов'),
        ),
        migrations.AlterUniqueTogether(
            name='eventvenue',
            unique_together=set([('city', 'slug')]),
        ),
        migrations.AlterUniqueTogether(
            name='eventlinkbinder',
            unique_together=set([('event', 'event_link')]),
        ),
        migrations.AlterUniqueTogether(
            name='eventcontainerbinder',
            unique_together=set([('event', 'event_container', 'order')]),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set([('domain', 'datetime', 'slug')]),
        ),
    ]
