# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcontainer',
            name='mode',
            field=models.CharField(choices=[('big_vertical', 'Большие вертикальные'), ('big_horizontal', 'Большие горизонтальные'), ('small_vertical', 'Маленькие вертикальные'), ('small_horizontal', 'Маленькие горизонтальные')], db_index=True, default='small_vertical', max_length=16, verbose_name='Тип контейнера'),
        ),
    ]
