# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20170721_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_service_prices',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Цены в сервисе продажи билетов'),
        ),
    ]
