# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 14:15
from __future__ import unicode_literals

import bezantrakta.event.models.link
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20170602_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventcontainerbinder',
            options={'ordering': ('order', 'event', 'event_container'), 'verbose_name': 'связь событий и контейнеров', 'verbose_name_plural': 'связь событий и контейнеров'},
        ),
        migrations.AlterField(
            model_name='eventlink',
            name='img',
            field=models.ImageField(blank=True, help_text='Размер логотипа 200x32 px', null=True, upload_to=bezantrakta.event.models.link.img_path, verbose_name='Логотип'),
        ),
    ]
