# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-10 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20171226_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_order_courier_cash',
            field=models.BooleanField(default=True, verbose_name='Доставка курьером'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_order_email_online',
            field=models.BooleanField(default=True, verbose_name='Оплатить онлайн и получить электронный билет на email'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_order_self_cash',
            field=models.BooleanField(default=True, verbose_name='Забронировать и выкупить в кассе'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_order_self_online',
            field=models.BooleanField(default=True, verbose_name='Оплатить онлайн и получить в кассе'),
        ),
    ]
