# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20170613_1857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventgroupbinder',
            options={'ordering': ('event_group', 'event'), 'verbose_name': 'связка событий и групп событий', 'verbose_name_plural': 'связки событий и групп событий'},
        ),
    ]
