# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20170602_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcontainer',
            name='img_height',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Высота афиши'),
        ),
        migrations.AlterField(
            model_name='eventcontainer',
            name='img_width',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ширина афиши'),
        ),
    ]
