# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20170605_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(max_length=64, unique_for_date='datetime', verbose_name='Псевдоним'),
        ),
    ]
