# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20170627_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcategory',
            name='description',
            field=models.TextField(help_text='Содержит ключевые слова или фразы, описывающие категорию, но не более 3-5 шт.<br>Всего не более 150-200 символов.', max_length=200, verbose_name='Метатег `description`'),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='keywords',
            field=models.TextField(help_text='Несколько ключевых слов или фраз, разделённых запятыми, которые описывают категорию.<br>Всего не более 100-150 символов.', max_length=150, verbose_name='Метатег `keywords`'),
        ),
        migrations.AlterField(
            model_name='eventcontainer',
            name='slug',
            field=models.SlugField(max_length=64, verbose_name='Псевдоним'),
        ),
        migrations.AlterField(
            model_name='eventcontainer',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Название'),
        ),
    ]
