# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, verbose_name='Название меню')),
                ('slug', models.SlugField(max_length=64, verbose_name='Псевдоним меню')),
                ('order', models.SmallIntegerField(verbose_name='Порядок в меню')),
            ],
            options={
                'verbose_name_plural': 'Меню',
                'db_table': 'bezantrakta_menu',
                'ordering': ('title', 'order'),
                'verbose_name': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, verbose_name='Название пункта меню')),
                ('slug', models.SlugField(help_text='Псевдоним пункта меню должен совпадать\n        с псевдонимом страницы, которую требуется в нём отобразить.', max_length=64, verbose_name='Псевдоним пункта меню')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('order', models.SmallIntegerField(verbose_name='Порядок в меню')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='Сохранено')),
                ('domain', models.ForeignKey(db_column='domain_id', on_delete=django.db.models.deletion.CASCADE, to='domain.Domain', verbose_name='Домен')),
                ('menu', models.ForeignKey(db_column='menu_id', on_delete=django.db.models.deletion.CASCADE, to='menu.Menu', verbose_name='Меню')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
                'db_table': 'bezantrakta_menu_item',
                'ordering': ('domain', 'menu', 'order', 'title'),
            },
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['id'], name='bezantrakta_id_a6cacf_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['id'], name='bezantrakta_id_b568b2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together=set([('domain', 'menu', 'slug')]),
        ),
    ]
