# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='domain',
            field=models.ForeignKey(db_column='domain_id', on_delete=django.db.models.deletion.CASCADE, to='location.Domain', verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='slug',
            field=models.SlugField(blank=True, help_text='При ссылке на страницу псевдоним пункта меню должен совпадать с псевдонимом страницы, которую требуется в нём отобразить.', max_length=64, verbose_name='Псевдоним'),
        ),
    ]
