# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='slug',
            field=models.SlugField(blank=True, help_text='При ссылке на страницу псевдоним пункта меню должен совпадать с псевдонимом страницы, которую требуется в нём отобразить.<br>Для главной страницы псевдоним должен быть пустым.', max_length=64, verbose_name='Псевдоним'),
        ),
    ]
