# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20170602_0901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ('order', 'domain', 'menu', 'title'), 'verbose_name': 'пункт меню', 'verbose_name_plural': 'пункты меню'},
        ),
    ]
