# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_unique_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderticket',
            name='price_group_id',
        ),
    ]
