# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_overall'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderticket',
            name='is_fixed',
            field=models.BooleanField(default=True, verbose_name='Сидячее место'),
        ),
        migrations.AddField(
            model_name='orderticket',
            name='ticket_id',
            field=models.CharField(max_length=32, null=True, verbose_name='ID билета'),
        ),
    ]
