# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='slug',
            field=models.SlugField(blank=True, help_text='Псевдоним пункта меню должен совпадать\n        с псевдонимом страницы, которую требуется в нём отобразить.', max_length=64, null=True, verbose_name='Псевдоним пункта меню'),
        ),
    ]
