# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20170523_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Порядок в меню'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.SlugField(max_length=32, verbose_name='Псевдоним меню'),
        ),
    ]
