# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20170524_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Порядок в меню'),
        ),
    ]
