# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20170524_1253'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='menuitem',
            name='bezantrakta_id_b568b2_idx',
        ),
        migrations.RemoveIndex(
            model_name='menu',
            name='bezantrakta_id_a6cacf_idx',
        ),
    ]
