# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20170524_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ('order', 'menu', 'domain', 'title'), 'verbose_name': 'Пункт меню', 'verbose_name_plural': 'Пункты меню'},
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок в меню'),
        ),
    ]
