# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20170524_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ('order', 'title'), 'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
    ]
