# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 17:32
from __future__ import unicode_literals

import bezantrakta.location.models
from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.IntegerField(help_text='Идентификатор города - его телефонный код.', primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('slug', models.SlugField(max_length=8, verbose_name='Псевдоним')),
                ('timezone', timezone_field.fields.TimeZoneField(default='Europe/Moscow', verbose_name='Часовой пояс')),
                ('state', models.NullBooleanField(choices=[(False, 'отключен'), (None, 'подготовка'), (True, 'включен')], default=False, help_text='<ul><li>отключен - НЕ виден в списке городов и НЕ работает;</li><li>подготовка - виден в списке городов, но НЕ доступен для выбора (скоро открытие);</li><li>включен - виден в списке городов и работает.</li></ul>', verbose_name='Состояние')),
            ],
            options={
                'verbose_name_plural': 'города',
                'db_table': 'bezantrakta_location_city',
                'ordering': ('title',),
                'verbose_name': 'город',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.IntegerField(help_text='Идентификатор сайта - число из 3-х цифр.<br>Первые 2 цифры - автомобильный код региона, в котором находится город сайта.<br><a href="https://ru.wikipedia.org/wiki/Коды_субъектов_Российской_Федерации" target="_blank">👉 Поиск автомобильного кода региона</a><br>Третья цифра - порядковый номер от 0 до 9.', primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('slug', models.CharField(help_text='<ul><li>Чтобы создать основной сайт в выбранном городе:<ul><li>псевдоним сайта должен совпадать с псевдонимом города,</li><li>последняя цифра идентификатора сайта - 0.</li></ul></li><li>Чтобы создать сайт какого-то учреждения в выбранном городе (например, ТОБ в Воронеже):<ul><li>псевдоним сайта может быть любым,</li><li>последняя цифра идентификатора сайта - от 1 до 9.</li></ul></li></ul>', max_length=32, unique=True, verbose_name='Псевдоним')),
                ('is_published', models.BooleanField(default=False, help_text='<ul><li>опубликован - включен и работает;</li><li>НЕ опубликован - отключен (сайт недоступен, проводятся технические работы).</li></ul>', verbose_name='Публикация')),
                ('settings', models.TextField(default=bezantrakta.location.models.get_default_domain_settings, help_text='<ul><li>{ <strong>domain</strong> } - информация о сайте в целом:<ul><li>string <strong>title</strong> - название сайта в теге `title`,</li><li>string <strong>description</strong> - метатег `description` для всего сайта,</li><li>string <strong>keywords</strong> - метатег `keywords` для всего сайта.</li></ul></li><li>{ <strong>webmaster</strong> } - регистрация в инструментах для вебмастеров:<ul><li>string <strong>yandex</strong> - Яндекс.Вебмастер,</li><li>string <strong>google</strong> - Google.SearchConsole.</li></ul></li><li>{ <strong>counter</strong> } - регистрация в счётчиках, собирающих информацию о посетителях сайта:<ul><li>string <strong>yandex</strong> - Яндекс.Метрика,</li><li>string <strong>google</strong> - Google.Analytics,</li><li>string <strong>uptolike</strong> - UpToLike (кнопки "Поделиться в соцсетях" и др.),</li><li>string <strong>vkontakte</strong> - пиксель ВКонтакте.</li></ul></li><li>{ <strong>email</strong> } - электронная почта для конкретных сайтов:<ul><li><del>string <strong>domain</strong> - общий email сайта,</del></li><li><del>string <strong>admin</strong> - email администраторов сайта.</del></li></ul></li><li>[ <strong>telephone</strong> ] - список телефонов для "Справок и бронирования":<ul><li>string телефоны в формате +7 (473) 210-01-02.</li></ul></li><li>[ <strong>social</strong> ] - список учётных записей сайта в соцсетях:<ul><li>{ учётные записи в соцсетях }<ul><li>string <strong>title</strong> - название соцсети,</li><li>string <strong>slug</strong> - псевдоним соцсети,</li><li>string <strong>href</strong> - ссылка на страницу в соцсети.</li></ul></li></ul></li><li>{ <strong>emailing</strong> } - информация о почтовой рассылке:<ul><li>boolean <strong>is_working</strong> - работает ли почтовая рассылка на сайте,</li><li>string <strong>text</strong> - сопроводительный текст при подписке на почтовую рассылку на сайте.</li></ul></li><li>{ <strong>order</strong> } - включение/отключение вариантов заказа билетов на сайте:<ul><li>boolean <strong>self</strong> - получение билетов в кассе (оплата наличными),</li><li>boolean <strong>courier</strong> - доставка курьером (оплата наличными),</li><li>boolean <strong>payment</strong> - получение билетов в кассе (онлайн-оплата),</li><li>boolean <strong>eticket</strong> - получение билетов на email (онлайн-оплата).</li></ul></li></ul>', verbose_name='Настройки в JSON')),
                ('city', models.ForeignKey(db_column='city_id', on_delete=django.db.models.deletion.CASCADE, to='location.City', verbose_name='Город')),
            ],
            options={
                'verbose_name_plural': 'сайты',
                'db_table': 'bezantrakta_location_domain',
                'ordering': ('city', 'title'),
                'verbose_name': 'сайт',
            },
        ),
    ]
