# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, verbose_name='Название города')),
                ('slug', models.SlugField(max_length=8, verbose_name='Псевдоним города')),
                ('timezone', timezone_field.fields.TimeZoneField(default='Europe/Moscow', verbose_name='Часовой пояс')),
                ('is_published', models.BooleanField(default=False, help_text='\n        True - включен и работает,\n        False - отключен (скоро открытие).', verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'город',
                'verbose_name_plural': 'города',
                'ordering': ('title',),
                'db_table': 'bezantrakta_location_city',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('slug', models.CharField(max_length=32, unique=True, verbose_name='Псевдоним')),
                ('is_published', models.BooleanField(default=False, help_text='\n        True - включен и работает,\n        False - отключен (сайт недоступен, проводятся технические работы).', verbose_name='Публикация')),
                ('city', models.ForeignKey(db_column='city_id', on_delete=django.db.models.deletion.CASCADE, to='location.City', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'домен',
                'verbose_name_plural': 'домены',
                'ordering': ('city', 'title'),
                'db_table': 'bezantrakta_location_domain',
            },
        ),
    ]
