# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.NullBooleanField(choices=[(False, 'отключен'), (None, 'подготовка'), (True, 'включен')], default=False, help_text='\n        <ul>\n        <li>отключен - НЕ виден в списке городов и НЕ работает;</li>\n        <li>подготовка - виден в списке городов, но НЕ доступен для выбора ("скоро открытие");</li>\n        <li>включен - виден в списке городов и работает.</li>\n        </ul>\n        ', verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(max_length=8, verbose_name='Псевдоним'),
        ),
        migrations.AlterField(
            model_name='city',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Название'),
        ),
    ]
