# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20170615_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='is_published',
        ),
    ]
