# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_remove_city_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'ordering': ('city', 'title'), 'verbose_name': 'сайт', 'verbose_name_plural': 'сайты'},
        ),
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.IntegerField(help_text='Идентификатор города - его телефонный код.', primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.NullBooleanField(choices=[(False, 'отключен'), (None, 'подготовка'), (True, 'включен')], default=False, help_text='<ul><li>отключен - НЕ виден в списке городов и НЕ работает;</li><li>подготовка - виден в списке городов, но НЕ доступен для выбора (скоро открытие);</li><li>включен - виден в списке городов и работает.</li></ul>', verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='id',
            field=models.IntegerField(help_text='Идентификатор сайта - число из 3-х цифр.<br>Первые 2 цифры - автомобильный код региона, в котором находится город сайта.<br>Третья цифра - порядковый номер от 0 до 9.', primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='is_published',
            field=models.BooleanField(default=False, help_text='<ul><li>опубликован - включен и работает;</li><li>НЕ опубликован - отключен (сайт недоступен, проводятся технические работы).</li></ul>', verbose_name='Публикация'),
        ),
    ]
