# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import domain.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('domain_id', models.IntegerField(primary_key=True, serialize=False)),
                ('domain_title', models.CharField(max_length=50, verbose_name='Название домена')),
                ('domain_slug', models.SlugField(max_length=100, unique=True, validators=[domain.models._domain_name_validator], verbose_name='Псевдоним домена')),
                ('city_id', models.ForeignKey(db_column='city_id', on_delete=django.db.models.deletion.CASCADE, to='city.City')),
            ],
            options={
                'verbose_name': 'Домен',
                'ordering': ('city_id', 'domain_title'),
                'verbose_name_plural': 'Домены',
                'db_table': 'bezantrakta_domain',
            },
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['domain_id'], name='bezantrakta_domain__05d6ab_idx'),
        ),
    ]
