# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='title',
            field=models.CharField(max_length=32, verbose_name='Название домена'),
        ),
    ]
