# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 10:11
from __future__ import unicode_literals

import bezantrakta.domain.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_auto_20170524_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='slug',
            field=models.SlugField(max_length=32, unique=True, validators=[bezantrakta.domain.models._domain_name_validator], verbose_name='Псевдоним домена'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Название домена'),
        ),
    ]
