# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0004_auto_20170524_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='is_online',
            field=models.BooleanField(default=False, help_text='\n        True - включен и работает,\n        False - отключен (сайт недоступен, проводятся технические работы).', verbose_name='Включен/отключен'),
        ),
    ]
