# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=64, verbose_name='Название города')),
                ('slug', models.SlugField(max_length=64, verbose_name='Псевдоним города')),
                ('status', models.BooleanField(default=False, help_text='True - готов к работе, False - скоро открытие', verbose_name='Готов ли город к работе')),
                ('timezone', timezone_field.fields.TimeZoneField(default='Europe/Moscow')),
            ],
            options={
                'verbose_name_plural': 'Города',
                'db_table': 'bezantrakta_city',
                'ordering': ('title',),
                'verbose_name': 'Город',
            },
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['id'], name='bezantrakta_id_d9951e_idx'),
        ),
    ]
