# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_auto_20170523_2150'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='city',
            name='bezantrakta_id_d9951e_idx',
        ),
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
